//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlippersFactory320AAE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Id_TypeSlippers { get; set; }
        public Nullable<int> ColSlippers { get; set; }
        public Nullable<int> Id_Warehouse { get; set; }
    
        public virtual TypeSlippers TypeSlippers { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
