//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlippersFactory320AAE.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlippersFactoryEntities : DbContext
    {
        public SlippersFactoryEntities()
            : base("name=SlippersFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Box> Box { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Plann> Plann { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<PurposeMachine> PurposeMachine { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeProvider> TypeProvider { get; set; }
        public virtual DbSet<TypeSlippers> TypeSlippers { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
