//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlippersFactory320AAE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plann
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NormO { get; set; }
        public Nullable<int> NormZ { get; set; }
        public Nullable<int> ColZSlippers { get; set; }
        public Nullable<int> ColOSlippers { get; set; }
        public Nullable<int> Id_Administrator { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
